// lib/dummy-data.ts
import type { QuoteDetail } from "@/types";

export const QUOTE_DETAILS: Record<string, QuoteDetail> = {
  "QT-2024-0718-001": {
    id: "QT-2024-0718-001",
    date: "2025-06-25",
    clientName: "Eagan Inc.",
    client: {
      clientType: "Company",
      companyName: "Eagan Inc.",
      contactPerson: "John Eagan",
      email: "john@eagan.com",
      phone: "501234567",
      countryCode: "+971",
      role: "Procurement Manager",
    },
    product: "Business Card",
    quantity: 1000,
    sides: "1",
    printing: "Digital",
    papers: [{ name: "BOOK", gsm: "300" }],
    finishing: ["UV Spot", "Lamination"],
    colors: { front: "4/0 CMYK + 2 PMS Colors" },
    amounts: { base: 2450, vat: 122.5, total: 2450, status: "Approved" },
  },

  "QT-2024-0719-002": {
    id: "QT-2024-0719-002",
    date: "2025-06-24",
    clientName: "Brightline Media",
    client: {
      clientType: "Company",
      companyName: "Brightline Media",
      contactPerson: "Emma White",
      email: "emma@brightline.io",
      phone: "6212345678",
      countryCode: "+62",
      role: "Brand Manager",
    },
    product: "Flyer A5",
    quantity: 5000,
    sides: "2",
    printing: "Offset",
    papers: [{ name: "Art Paper", gsm: "150" }],
    finishing: ["Lamination"],
    colors: { front: "4/4 CMYK", back: "4/4 CMYK" },
    amounts: { base: 1800, vat: 90, total: 1890, status: "Approved" },
  },

  "QT-2024-0720-003": {
    id: "QT-2024-0720-003",
    date: "2025-06-23",
    clientName: "Orion Books",
    client: {
      clientType: "Company",
      companyName: "Orion Books",
      contactPerson: "Liam Carter",
      email: "liam@orionbooks.com",
      phone: "15551234567",
      countryCode: "+1",
      role: "Publishing Lead",
    },
    product: "Book",
    quantity: 300,
    sides: "2",
    printing: "Offset",
    papers: [{ name: "HVS", gsm: "80" }],
    finishing: ["UV Spot", "Foil Stamping"],
    colors: { front: "4/4 CMYK + 1 PMS", back: "4/4 CMYK + 1 PMS" },
    amounts: { base: 3200, vat: 160, total: 3360, status: "Approved" },
  },

  "QT-2024-0721-004": {
    id: "QT-2024-0721-004",
    date: "2025-06-22",
    clientName: "TechCorp Solutions",
    client: {
      clientType: "Company",
      companyName: "TechCorp Solutions",
      contactPerson: "Sarah Johnson",
      email: "sarah@techcorp.com",
      phone: "15551234568",
      countryCode: "+1",
      role: "Marketing Director",
    },
    product: "Brochure",
    quantity: 2000,
    sides: "2",
    printing: "Digital",
    papers: [{ name: "Glossy", gsm: "200" }],
    finishing: ["Lamination"],
    colors: { front: "4/4 CMYK", back: "4/4 CMYK" },
    amounts: { base: 1200, vat: 60, total: 1260, status: "Pending" },
  },

  "QT-2024-0722-005": {
    id: "QT-2024-0722-005",
    date: "2025-06-21",
    clientName: "Global Industries",
    client: {
      clientType: "Company",
      companyName: "Global Industries",
      contactPerson: "Michael Chen",
      email: "michael@global.com",
      phone: "15551234569",
      countryCode: "+1",
      role: "Operations Manager",
    },
    product: "Poster",
    quantity: 500,
    sides: "1",
    printing: "Offset",
    papers: [{ name: "Art Paper", gsm: "250" }],
    finishing: ["UV Spot"],
    colors: { front: "4/4 CMYK + 2 PMS Colors" },
    amounts: { base: 800, vat: 40, total: 840, status: "Approved" },
  },

  "QT-2024-0723-006": {
    id: "QT-2024-0723-006",
    date: "2025-06-20",
    clientName: "Creative Agency",
    client: {
      clientType: "Company",
      companyName: "Creative Agency",
      contactPerson: "Lisa Rodriguez",
      email: "lisa@creative.com",
      phone: "15551234570",
      countryCode: "+1",
      role: "Creative Director",
    },
    product: "Catalog",
    quantity: 1500,
    sides: "2",
    printing: "Offset",
    papers: [{ name: "HVS", gsm: "120" }],
    finishing: ["Perfect Binding"],
    colors: { front: "4/4 CMYK", back: "4/4 CMYK" },
    amounts: { base: 2800, vat: 140, total: 2940, status: "Approved" },
  },

  "QT-2024-0724-007": {
    id: "QT-2024-0724-007",
    date: "2025-06-19",
    clientName: "Startup Ventures",
    client: {
      clientType: "Company",
      companyName: "Startup Ventures",
      contactPerson: "David Kim",
      email: "david@startup.com",
      phone: "15551234571",
      countryCode: "+1",
      role: "Founder",
    },
    product: "Business Cards",
    quantity: 500,
    sides: "1",
    printing: "Digital",
    papers: [{ name: "BOOK", gsm: "300" }],
    finishing: ["UV Spot"],
    colors: { front: "4/0 CMYK + 1 PMS Color" },
    amounts: { base: 400, vat: 20, total: 420, status: "Rejected" },
  },

  "QT-2024-0725-008": {
    id: "QT-2024-0725-008",
    date: "2025-06-18",
    clientName: "Enterprise Corp",
    client: {
      clientType: "Company",
      companyName: "Enterprise Corp",
      contactPerson: "Jennifer Smith",
      email: "jennifer@enterprise.com",
      phone: "15551234572",
      countryCode: "+1",
      role: "Procurement Manager",
    },
    product: "Annual Report",
    quantity: 1000,
    sides: "2",
    printing: "Offset",
    papers: [{ name: "Art Paper", gsm: "200" }],
    finishing: ["Perfect Binding", "Foil Stamping"],
    colors: { front: "4/4 CMYK + 2 PMS Colors", back: "4/4 CMYK + 2 PMS Colors" },
    amounts: { base: 4500, vat: 225, total: 4725, status: "Approved" },
  },

  "QT-2024-0726-009": {
    id: "QT-2024-0726-009",
    date: "2025-06-17",
    clientName: "Innovation Labs",
    client: {
      clientType: "Company",
      companyName: "Innovation Labs",
      contactPerson: "Robert Wilson",
      email: "robert@innovation.com",
      phone: "15551234573",
      countryCode: "+1",
      role: "R&D Director",
    },
    product: "Technical Manual",
    quantity: 800,
    sides: "2",
    printing: "Digital",
    papers: [{ name: "HVS", gsm: "100" }],
    finishing: ["Spiral Binding"],
    colors: { front: "4/4 CMYK", back: "4/4 CMYK" },
    amounts: { base: 1600, vat: 80, total: 1680, status: "Pending" },
  },

  "QT-2024-0727-010": {
    id: "QT-2024-0727-010",
    date: "2025-06-16",
    clientName: "Marketing Pro",
    client: {
      clientType: "Company",
      companyName: "Marketing Pro",
      contactPerson: "Amanda Davis",
      email: "amanda@marketingpro.com",
      phone: "15551234574",
      countryCode: "+1",
      role: "Marketing Manager",
    },
    product: "Promotional Materials",
    quantity: 3000,
    sides: "1",
    printing: "Offset",
    papers: [{ name: "Glossy", gsm: "150" }],
    finishing: ["Lamination"],
    colors: { front: "4/4 CMYK + 1 PMS Color" },
    amounts: { base: 2100, vat: 105, total: 2205, status: "Approved" },
  }
};

// Function to get quotes for dashboard table
export function getQuotes() {
  return Object.values(QUOTE_DETAILS).map(quote => ({
    id: quote.id,
    quoteNumber: quote.id,
    customerName: quote.clientName,
    jobType: quote.product,
    status: quote.amounts.status,
    totalAmount: quote.amounts.total.toFixed(2),
    createdDate: quote.date,
    contactPerson: quote.client.contactPerson,
    quantity: quote.quantity,
    printing: quote.printing,
    sides: quote.sides
  }));
}
